create table if not exists public.annotations (
  id bigint generated by default as identity primary key,
  page integer not null check (page > 0),
  x double precision not null check (x >= 0 and x <= 1),
  y double precision not null check (y >= 0 and y <= 1),
  mode text not null default 'point',
  points text,
  value double precision not null,
  unit text not null,
  category text not null,
  comment text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists annotations_created_at_idx
  on public.annotations (created_at asc);

create table if not exists public.annotation_events (
  id bigint generated by default as identity primary key,
  annotation_id bigint,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists annotation_events_created_at_idx
  on public.annotation_events (created_at desc);
